type: application
version: v4.0.0
data:
  applicationInfo:
    applicationId: 4ac39ec5-f375-4497-be73-6ebb49e16b3c
    name: DilrukApp1
    throttlingPolicy: 10PerMin
    description: 'DilrukApp1 Description '
    tokenType: JWT
    status: APPROVED
    groups: []
    subscriptionCount: 1
    keys: []
    attributes: {}
    subscriptionScopes: []
    owner: admin
  subscribedAPIs:
   -
    apiId:
      providerName: admin
      apiName: SampleAPI1
      version: 1.0.0
      id: 0
    subscriber:
      name: admin
      id: 1
      tenantId: 0
    throttlingPolicy: Unlimited
